[build]
  functions = "netlify/functions"

[dev]
  framework = "#static" # Use this to avoid any local server issues

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Redirect all requests to your serverless function
  status = 200