[build]
  functions = "netlify/functions" # Path to your function directory
  publish = "build"  # Or your project's build directory if you have one. If you don't have a build step, you can omit the publish key.

[dev]
  framework = "#static" # Use this to avoid any local server issues

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Redirect all requests to your serverless function
  status = 200